// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package jp.com.inotaku.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import jp.com.inotaku.domain.Book;
import jp.com.inotaku.domain.BookDataOnDemand;
import jp.com.inotaku.repository.BookRipository;
import jp.com.inotaku.service.BookService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BookDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookDataOnDemand: @Component;
    
    private Random BookDataOnDemand.rnd = new SecureRandom();
    
    private List<Book> BookDataOnDemand.data;
    
    @Autowired
    BookService BookDataOnDemand.bookService;
    
    @Autowired
    BookRipository BookDataOnDemand.bookRipository;
    
    public Book BookDataOnDemand.getNewTransientBook(int index) {
        Book obj = new Book();
        setBookId(obj, index);
        setBookName(obj, index);
        setPrice(obj, index);
        return obj;
    }
    
    public void BookDataOnDemand.setBookId(Book obj, int index) {
        Long bookId = new Integer(index).longValue();
        obj.setBookId(bookId);
    }
    
    public void BookDataOnDemand.setBookName(Book obj, int index) {
        String bookName = "bookName_" + index;
        obj.setBookName(bookName);
    }
    
    public void BookDataOnDemand.setPrice(Book obj, int index) {
        int price = index;
        if (price < 0) {
            price = 0;
        }
        obj.setPrice(price);
    }
    
    public Book BookDataOnDemand.getSpecificBook(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Book obj = data.get(index);
        Long id = obj.getId();
        return bookService.findBook(id);
    }
    
    public Book BookDataOnDemand.getRandomBook() {
        init();
        Book obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return bookService.findBook(id);
    }
    
    public boolean BookDataOnDemand.modifyBook(Book obj) {
        return false;
    }
    
    public void BookDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = bookService.findBookEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Book' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Book>();
        for (int i = 0; i < 10; i++) {
            Book obj = getNewTransientBook(i);
            try {
                bookService.saveBook(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            bookRipository.flush();
            data.add(obj);
        }
    }
    
}
